### ISSUE TITLE
Incorrect function names in README file and not clear example for hooks

### ISSUE THREAD

**Issue by okvorb** [defold/extension-poco#2]
There are several errors in the README file. You have used function names that are missing in poco namespace:

```
poco:setDispatchFn
poco:setDispatchCallbackFn

```

Correct names:

```
poco:set_dispatch_fn
poco:set_dispatch_callback_fn

```
I don't understand how to use hooks. Can you provide more real life examples? 

What is the point to use hook for dump function? Can I make a hook for an arbitrary function in the game?
```
    poco:set_dispatch_callback_fn("Dump", function(scene)
        pprint("INSIDE NEW CALLBACK FUNCTION!", scene)
        return scene
    end)

```

**Comment by JCash** [comment]
Thanks!
The typos should be fixed now.

> I don't understand how to use hooks. Can you provide more real life examples?

Well, I don't actually have a very good example (yet).
Essentially, the hook is there to allow the developer (you) to manipulate the returned value _just before_ it's being returned to the caller (the Python client).

> What is the point to use hook for dump function?

Overriding the "Dump" function allows you to add/remove objects to the reported scene graph (from the callers perspective, not the game itself). You can also change/add/remove properties of these objects, to suit your testing needs.
You might for instance want to add a "meta data" object that holds some statistics over the game: number of levels played, number of failed login attempts etc.

Another example could be overriding the "GetScreenSize" allows you to manipulate the reported screen size. (No tsure why that would be useful, it's just an example).

> Can I make a hook for an arbitrary function in the game?

Here I feel you're not really asking about the Poco functionality itself.
In Lua, you can monkey patch any function like so:

```lua
local oldfn = pprint
pprint = function (t) -- override the pprint name
    print "THE PPRINT FUNCTION IS OVERRIDDEN!"
    oldfn(t) -- call the old pprint
end
```

This however is not really related to the Poco extension functionality.
You can add custom functions via `poco::set_dispatch_fn()`, which allows you to call this function from the client (Python) side.

Perhaps if you can explain in more detail of what you wanted to do?

**Comment by okvorb** [comment]
Thanks a lot for quick reply. It was very helpful for me.
