### ISSUE TITLE
"visible" attribute is always set to true for any node

### ISSUE THREAD

**Issue by dmaluev-ms** [defold/extension-poco#4]
In Poco hierarchy dump "visible" attribute is always set to true for any node. Can this be changed to show whether the node is actually visible or not (enabled or disabled)?

**Comment by AGulev** [comment]
@dmaluev-ms
I'm going to add new `enabled` field with `true`/`false` values.
Do you need it only for nodes in gui?

**Comment by dmaluev-ms** [comment]
Yes, currently only for GUI. To check if the button is visible or not, for example.

**Comment by AGulev** [comment]
The `visible` field is booked for another reason, I added `enabled` field for nodes and some components (sprites, labels etc)

You can take a look this PR:
https://github.com/defold/defold/pull/6355
